name: First CI/CD Pipeline
on:
  push:
    branches: 
      - mainapp
      - develop
jobs:
  build:
    runs-on: server1
    steps:
    - name: Print Hello world
      run: |
        echo "I am build stage"
        ip a
  test:
    needs: build
    runs-on: server1 
    steps:
    - name: Print Hello world
      run: |
        echo "I am test stage"
        ip a
  release:
    needs: test
    runs-on: server1
    steps:
    - name: Print Hello world
      run: |
        echo "I am release "
        ip a
        hostname